services:
  node:
    container_name: node
    build: ./node
    image: node
    volumes:
      - ./node/res:/home/apriego-/node
      - node_data:/home/apriego-/node/res/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-network
  django:
    container_name: django
    build: ./django
    image: django
    volumes:
      - django_data:/home/apriego-/django/
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
  postgres:
    build: ./postgreSQL
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/home/apriego-/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
volumes:
  node_data:
    driver: local
    driver_opts:
      device: "./node/res/node_modules"
      o: bind
      type: none
  django_data:
    driver: local
    driver_opts:
      device: "./django/res"
      o: bind
      type: none
  postgres_data:
    driver: local
    driver_opts:
      device: "./postgreSQL/res"
      o: bind
      type: none

networks:
  app-network:
      name: app-network
      driver: bridge